# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/microsoft/winget-cli/master/schemas/JSON/manifests/v1.0.0/manifest.defaultLocale.1.0.0.json
#   timestamp: 2022-07-05T19:20:35+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, constr


class Url(BaseModel):
    __root__: Optional[
        constr(regex=r'^([Hh][Tt][Tt][Pp][Ss]?)://.+$', max_length=2048)
    ] = Field(..., description='Optional Url type')


class Tag(BaseModel):
    __root__: Optional[constr(min_length=1, max_length=40)] = Field(
        ..., description='Package moniker or tag'
    )


class Model(BaseModel):
    PackageIdentifier: constr(
        regex=r'^[^\.\s\\/:\*\?"<>\|\x01-\x1f]{1,32}(\.[^\.\s\\/:\*\?"<>\|\x01-\x1f]{1,32}){1,3}$',
        max_length=128,
    ) = Field(..., description='The package unique identifier')
    PackageVersion: constr(
        regex=r'^[^\\/:\*\?"<>\|\x01-\x1f]+$', max_length=128
    ) = Field(..., description='The package version')
    PackageLocale: constr(
        regex=r'^([a-zA-Z]{2,3}|[iI]-[a-zA-Z]+|[xX]-[a-zA-Z]{1,8})(-[a-zA-Z]{1,8})*$',
        max_length=20,
    ) = Field(..., description='The package meta-data locale')
    Publisher: constr(min_length=2, max_length=256) = Field(
        ..., description='The publisher name'
    )
    PublisherUrl: Optional[Url] = Field(None, description='The publisher home page')
    PublisherSupportUrl: Optional[Url] = Field(
        None, description='The publisher support page'
    )
    PrivacyUrl: Optional[Url] = Field(
        None, description='The publisher privacy page or the package privacy page'
    )
    Author: Optional[Optional[constr(min_length=2, max_length=256)]] = Field(
        None, description='The package author'
    )
    PackageName: constr(min_length=2, max_length=256) = Field(
        ..., description='The package name'
    )
    PackageUrl: Optional[Url] = Field(None, description='The package home page')
    License: constr(min_length=3, max_length=512) = Field(
        ..., description='The package license'
    )
    LicenseUrl: Optional[Url] = Field(None, description='The license page')
    Copyright: Optional[Optional[constr(min_length=3, max_length=512)]] = Field(
        None, description='The package copyright'
    )
    CopyrightUrl: Optional[Url] = Field(None, description='The package copyright page')
    ShortDescription: constr(min_length=3, max_length=256) = Field(
        ..., description='The short package description'
    )
    Description: Optional[Optional[constr(min_length=3, max_length=10000)]] = Field(
        None, description='The full package description'
    )
    Moniker: Optional[Tag] = Field(None, description='The most common package term')
    Tags: Optional[List[Tag]] = Field(
        None,
        description='List of additional package search terms',
        max_items=16,
        unique_items=True,
    )
    ManifestType: str = Field(..., description='The manifest type')
    ManifestVersion: constr(
        regex=r'^(0|[1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])(\.(0|[1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])){2}$'
    ) = Field(..., description='The manifest syntax version')
