# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/microsoft/winget-cli/master/schemas/JSON/manifests/v1.1.0/manifest.locale.1.1.0.json
#   timestamp: 2022-07-27T01:37:23+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, constr


class Url(BaseModel):
    __root__: Optional[
        constr(regex=r'^([Hh][Tt][Tt][Pp][Ss]?)://.+$', max_length=2048)
    ] = Field(..., description='Optional Url type')


class Tag(BaseModel):
    __root__: Optional[constr(min_length=1, max_length=40)] = Field(
        ..., description='Package tag'
    )


class Agreement(BaseModel):
    AgreementLabel: Optional[Optional[constr(min_length=1, max_length=100)]] = Field(
        None,
        description='The label of the Agreement. i.e. EULA, AgeRating, etc. This field should be localized. Either Agreement or AgreementUrl is required. When we show the agreements, we would Bold the AgreementLabel',
    )
    Agreement: Optional[Optional[constr(min_length=1, max_length=10000)]] = Field(
        None, description='The agreement text content.'
    )
    AgreementUrl: Optional[Url] = Field(None, description='The agreement URL.')


class Model(BaseModel):
    PackageIdentifier: constr(
        regex=r'^[^\.\s\\/:\*\?"<>\|\x01-\x1f]{1,32}(\.[^\.\s\\/:\*\?"<>\|\x01-\x1f]{1,32}){1,3}$',
        max_length=128,
    ) = Field(..., description='The package unique identifier')
    PackageVersion: constr(
        regex=r'^[^\\/:\*\?"<>\|\x01-\x1f]+$', max_length=128
    ) = Field(..., description='The package version')
    PackageLocale: constr(
        regex=r'^([a-zA-Z]{2,3}|[iI]-[a-zA-Z]+|[xX]-[a-zA-Z]{1,8})(-[a-zA-Z]{1,8})*$',
        max_length=20,
    ) = Field(..., description='The package meta-data locale')
    Publisher: Optional[Optional[constr(min_length=2, max_length=256)]] = Field(
        None, description='The publisher name'
    )
    PublisherUrl: Optional[Url] = Field(None, description='The publisher home page')
    PublisherSupportUrl: Optional[Url] = Field(
        None, description='The publisher support page'
    )
    PrivacyUrl: Optional[Url] = Field(
        None, description='The publisher privacy page or the package privacy page'
    )
    Author: Optional[Optional[constr(min_length=2, max_length=256)]] = Field(
        None, description='The package author'
    )
    PackageName: Optional[Optional[constr(min_length=2, max_length=256)]] = Field(
        None, description='The package name'
    )
    PackageUrl: Optional[Url] = Field(None, description='The package home page')
    License: Optional[Optional[constr(min_length=3, max_length=512)]] = Field(
        None, description='The package license'
    )
    LicenseUrl: Optional[Url] = Field(None, description='The license page')
    Copyright: Optional[Optional[constr(min_length=3, max_length=512)]] = Field(
        None, description='The package copyright'
    )
    CopyrightUrl: Optional[Url] = Field(None, description='The package copyright page')
    ShortDescription: Optional[Optional[constr(min_length=3, max_length=256)]] = Field(
        None, description='The short package description'
    )
    Description: Optional[Optional[constr(min_length=3, max_length=10000)]] = Field(
        None, description='The full package description'
    )
    Tags: Optional[List[Tag]] = Field(
        None,
        description='List of additional package search terms',
        max_items=16,
        unique_items=True,
    )
    Agreements: Optional[List[Agreement]] = Field(None, max_items=128)
    ReleaseNotes: Optional[Optional[constr(min_length=1, max_length=10000)]] = Field(
        None, description='The package release notes'
    )
    ReleaseNotesUrl: Optional[Url] = Field(
        None, description='The package release notes url'
    )
    ManifestType: str = Field(..., description='The manifest type')
    ManifestVersion: constr(
        regex=r'^(0|[1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])(\.(0|[1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])){2}$'
    ) = Field(..., description='The manifest syntax version')
